export const TYPOGRAPHY = {
  display: {
    fontFamily: "var(--font-display, 'Cormorant Garamond', serif)",
    fontSize: "clamp(3rem, 6vw, 5.5rem)",
    lineHeight: "0.95",
    letterSpacing: "-0.04em",
    fontWeight: 500,
  },
  h1: {
    fontFamily: "var(--font-display, 'Cormorant Garamond', serif)",
    fontSize: "clamp(2.5rem, 4.8vw, 4.25rem)",
    lineHeight: "1.02",
    letterSpacing: "-0.035em",
    fontWeight: 500,
  },
  h2: {
    fontFamily: "var(--font-display, 'Cormorant Garamond', serif)",
    fontSize: "clamp(2rem, 3.5vw, 3.25rem)",
    lineHeight: "1.08",
    letterSpacing: "-0.03em",
    fontWeight: 500,
  },
  h3: {
    fontFamily: "var(--font-display, 'Cormorant Garamond', serif)",
    fontSize: "clamp(1.5rem, 2.4vw, 2rem)",
    lineHeight: "1.15",
    letterSpacing: "-0.02em",
    fontWeight: 500,
  },
  h4: {
    fontFamily: "var(--font-display, 'Cormorant Garamond', serif)",
    fontSize: "clamp(1.25rem, 1.8vw, 1.5rem)",
    lineHeight: "1.2",
    letterSpacing: "-0.015em",
    fontWeight: 500,
  },
  bodyLarge: {
    fontFamily: "var(--font-body, 'Inter', sans-serif)",
    fontSize: "1.125rem",
    lineHeight: "1.75",
    letterSpacing: "-0.01em",
    fontWeight: 400,
  },
  body: {
    fontFamily: "var(--font-body, 'Inter', sans-serif)",
    fontSize: "1rem",
    lineHeight: "1.7",
    letterSpacing: "-0.005em",
    fontWeight: 400,
  },
  caption: {
    fontFamily: "var(--font-body, 'Inter', sans-serif)",
    fontSize: "0.875rem",
    lineHeight: "1.5",
    letterSpacing: "0.02em",
    fontWeight: 400,
  },
  label: {
    fontFamily: "var(--font-body, 'Inter', sans-serif)",
    fontSize: "0.8125rem",
    lineHeight: "1.3",
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    fontWeight: 600,
  },
  button: {
    fontFamily: "var(--font-body, 'Inter', sans-serif)",
    fontSize: "0.9375rem",
    lineHeight: "1.2",
    letterSpacing: "-0.01em",
    fontWeight: 600,
  },
  form: {
    fontFamily: "var(--font-body, 'Inter', sans-serif)",
    fontSize: "0.9375rem",
    lineHeight: "1.5",
    letterSpacing: "-0.005em",
    fontWeight: 400,
  },
} as const;